# Imagen base para ejecutar la app (runtime)
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

# Imagen para compilar la app (SDK)
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Copia los archivos del proyecto y restaura dependencias
COPY ["TicketService.csproj", "./"]
RUN dotnet restore "TicketService.csproj"

# Copia todo el código
COPY . .

# Instala certificados SSL para MongoDB Atlas
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

# Publica la app en Release
RUN dotnet publish "TicketService.csproj" -c Release -o /app/publish

# Imagen final liviana para ejecutar
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "TicketService.dll"]
